name: Deploy on Okteto

on:
   push:
     branches:    
      - master
     paths:
      - 'EFTGCA-VertxBackend/**'
      - '.github/workflows/deploy-okteto.yml'
env:
  OKTETO_NAMESPACE: 'mscarceller'
  GITHUBREPOSITORY: 'mscarceller'
  IMAGENAME: 'webchat'
  IMAGETAG: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ${OKTETO_NAMESPACE}

      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}  
        with:
          namespace: ${OKTETO_NAMESPACE}
          manifest: k8s.yml
          tag: ${GITHUBREPOSITORY}/${IMAGENAME}:${IMAGETAG}
          waitOn: deployment/webchat

