name: Deploy on Okteto

on:
   push:
     branches:    
      - master
     paths:
      - 'EFTGCA-VertxBackend/**'
      - '.github/workflows/deploy-okteto.yml'
env:
  OKTETO_NAMESPACE: 'mscarceller'
  GITHUBREPOSITORY: 'mscarceller'
  IMAGENAME: 'webchat'
  IMAGETAG: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: "Login into Okteto"
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: ${OKTETO_NAMESPACE}
    
    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        namespace: ${OKTETO_NAMESPACE}
        manifest: ./EFTGCA-VertxBackend/k8s.yaml
        