name: Node.js Package
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        working-directory: EFTGCA-MessagesLib
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
      working-directory: EFTGCA-MessagesLib
    - run: npm publish
      working-directory: EFTGCA-MessagesLib
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
